---

- name: Debug
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Say Hello Ansible
      debug: msg='Hello Ansible'

- name: Set up docker container
  hosts: all
  gather_facts: False

  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - python3
          - python3-pip
          - docker.io
        state: latest
        # very important if you want to install sytem packages
        update_cache: yes
      become: yes

    - name: Install Docker SDK for Python
      pip:
        name: ['docker']
        executable: pip3
      become: yes

    - name: Create a sample container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - 80:80
      become: yes
